package com.babydev.app.domain.entity;

// GENERATED WITH CHAT GPT
public enum DevelopmentSkill {
    MAVEN("Maven"),
    PYTHON("Python"),
    JAVASCRIPT("JavaScript"),
    JAVA("Java"),
    C_PLUS_PLUS("C++"),
    C_SHARP("C#"),
    RUBY("Ruby"),
    PHP("PHP"),
    SWIFT("Swift"),
    GO("Go"),
    RUST("Rust"),
    KOTLIN("Kotlin"),
    TYPESCRIPT("TypeScript"),
    SQL("SQL"),
    HTML_CSS("HTML/CSS"),
    REACT("React"),
    ANGULAR("Angular"),
    VUE_JS("Vue.js"),
    NODE_JS("Node.js"),
    DJANGO("Django"),
    FLASK("Flask"),
    SPRING_FRAMEWORK("Spring Framework"),
    RUBY_ON_RAILS("Ruby on Rails"),
    ASP_DOT_NET("ASP.NET"),
    UNITY("Unity"),
    UNREAL_ENGINE("Unreal Engine"),
    XAMARIN("Xamarin"),
    TENSORFLOW("TensorFlow"),
    PYTORCH("PyTorch"),
    MACHINE_LEARNING("Machine Learning"),
    DEEP_LEARNING("Deep Learning"),
    NATURAL_LANGUAGE_PROCESSING("NLP"),
    COMPUTER_VISION("Computer Vision"),
    DATA_SCIENCE("Data Science"),
    DATA_ANALYSIS("Data Analysis"),
    BIG_DATA("Big Data"),
    HADOOP("Hadoop"),
    SPARK("Spark"),
    NO_SQL("NoSQL (e.g., MongoDB, Cassandra)"),
    RELATIONAL_DATABASES("Relational Databases (e.g., MySQL, PostgreSQL, Oracle)"),
    DEVOPS("DevOps"),
    DOCKER("Docker"),
    KUBERNETES("Kubernetes"),
    JENKINS("Jenkins"),
    GIT("Git"),
    AGILE_METHODOLOGIES("Agile Methodologies"),
    SCRUM("Scrum"),
    KANBAN("Kanban"),
    TEST_DRIVEN_DEVELOPMENT("Test-Driven Development (TDD)"),
    CI_CD("Continuous Integration/Continuous Deployment (CI/CD)"),
    MICROSERVICES("Microservices"),
    RESTFUL_APIS("RESTful APIs"),
    GRAPHQL("GraphQL"),
    AWS("Amazon Web Services (AWS)"),
    AZURE("Microsoft Azure"),
    GOOGLE_CLOUD_PLATFORM("Google Cloud Platform (GCP)"),
    INFRASTRUCTURE_AS_CODE("Infrastructure as Code (IaC)"),
    LINUX("Linux"),
    BASH_SCRIPTING("Bash Scripting"),
    WINDOWS_SERVER("Windows Server"),
    NETWORKING("Networking"),
    CYBERSECURITY("Cybersecurity"),
    PENETRATION_TESTING("Penetration Testing"),
    CRYPTOGRAPHY("Cryptography"),
    BLOCKCHAIN("Blockchain"),
    IOT("Internet of Things (IoT)"),
    EMBEDDED_SYSTEMS("Embedded Systems"),
    ARDUINO("Arduino"),
    RASPBERRY_PI("Raspberry Pi"),
    VHDL("VHDL"),
    VERILOG("Verilog"),
    FPGA_PROGRAMMING("FPGA Programming"),
    PCB_DESIGN("PCB Design"),
    CIRCUIT_DESIGN("Circuit Design"),
    MICROCONTROLLERS("Microcontrollers (e.g., Arduino, Raspberry Pi, STM32)"),
    WIRELESS_COMMUNICATION("Wireless Communication (e.g., Bluetooth, Wi-Fi)"),
    MOBILE_APP_DEVELOPMENT("Mobile App Development (iOS/Android)"),
    FLUTTER("Flutter"),
    XAMARIN_FORMS("Xamarin.Forms"),
    REACT_NATIVE("React Native"),
    IONIC("Ionic"),
    NATIVESCRIPT("NativeScript"),
    GAME_DEVELOPMENT("Game Development"),
    VIRTUAL_REALITY("Virtual Reality (VR)"),
    AUGMENTED_REALITY("Augmented Reality (AR)"),
    OPENGL("OpenGL"),
    DIRECTX("DirectX"),
    UNREAL_ENGINE_BLUEPRINT("Unreal Engine Blueprint"),
    GAME_DESIGN("Game Design"),
    UI_UX_DESIGN("UI/UX Design"),
    ADOBE_CREATIVE_SUITE("Adobe Creative Suite"),
    SKETCH("Sketch"),
    FIGMA("Figma"),
    PROTOTYPING("Prototyping"),
    RESPONSIVE_WEB_DESIGN("Responsive Web Design"),
    CROSS_PLATFORM_DEVELOPMENT("Cross-Platform Development"),
    GRAPHQL_2("GraphQL"),
    FIREBASE("Firebase"),
    MICROSOFT_OFFICE_SUITE("Microsoft Office Suite"),
    PROJECT_MANAGEMENT("Project Management"),
    LEADERSHIP("Leadership"),
    COMMUNICATION("Communication"),
    PROBLEM_SOLVING("Problem Solving"),
    ALGORITHMS("Algorithms"),
    DATA_STRUCTURES("Data Structures"),
    OBJECT_ORIENTED_PROGRAMMING("Object-Oriented Programming (OOP)"),
    FUNCTIONAL_PROGRAMMING("Functional Programming"),
    SOFTWARE_ARCHITECTURE("Software Architecture"),
    DESIGN_PATTERNS("Design Patterns"),
    AGILE_DEVELOPMENT("Agile Development"),
    VERSION_CONTROL("Version Control"),
    CODE_REVIEW("Code Review"),
    SOFTWARE_TESTING("Software Testing"),
    DEBUGGING("Debugging"),
    PERFORMANCE_OPTIMIZATION("Performance Optimization"),
    USER_TESTING("User Testing"),
    DOCUMENTATION("Documentation"),
    TECHNICAL_WRITING("Technical Writing"),
    API_DESIGN("API Design"),
    FRONT_END_DEVELOPMENT("Front-End Development"),
    BACK_END_DEVELOPMENT("Back-End Development"),
    FULL_STACK_DEVELOPMENT("Full-Stack Development"),
    MOBILE_FIRST_DEVELOPMENT("Mobile-First Development"),
    RESPONSIVE_WEB_DESIGN_2("Responsive Web Design"),
    ACCESSIBILITY_STANDARDS("Accessibility Standards"),
    SEO("Search Engine Optimization (SEO)"),
    CONTENT_MANAGEMENT_SYSTEMS("Content Management Systems (CMS)"),
    WORDPRESS("WordPress"),
    DRUPAL("Drupal"),
    JOOMLA("Joomla"),
    SHOPIFY("Shopify"),
    ECOMMERCE_DEVELOPMENT("E-commerce Development"),
    PAYMENT_GATEWAYS("Payment Gateways"),
    SECURITY_TESTING("Security Testing"),
    QUALITY_ASSURANCE("Quality Assurance (QA)"),
    USER_INTERFACE_DESIGN("User Interface (UI) Design"),
    USER_EXPERIENCE_DESIGN("User Experience (UX) Design"),
    WIREFRAMING("Wireframing"),
    USER_RESEARCH("User Research"),
    DESIGN_THINKING("Design Thinking"),
    CLOUD_COMPUTING("Cloud Computing"),
    SERVERLESS_ARCHITECTURE("Serverless Architecture"),
    MICROSERVICES_ARCHITECTURE("Microservices Architecture"),
    SCALABILITY("Scalability"),
    PERFORMANCE_MONITORING("Performance Monitoring"),
    LOGGING_MONITORING_TOOLS("Logging and Monitoring Tools"),
    VIRTUALIZATION("Virtualization"),
    DATA_WAREHOUSING("Data Warehousing"),
    ETL("ETL (Extract, Transform, Load)"),
    DATA_VISUALIZATION("Data Visualization"),
    STATISTICAL_ANALYSIS("Statistical Analysis"),
    IMAGE_PROCESSING("Image Processing"),
    ROBOTICS("Robotics"),
    ARTIFICIAL_INTELLIGENCE("Artificial Intelligence (AI)"),
    CHATBOT_DEVELOPMENT("Chatbot Development"),
    NATURAL_LANGUAGE_GENERATION("Natural Language Generation (NLG)"),
    AUGMENTED_REALITY_2("Augmented Reality (AR)"),
    VIRTUAL_REALITY_2("Virtual Reality (VR)"),
    BIOMETRICS("Biometrics"),
    CRYPTOCURRENCY("Cryptocurrency"),
    SMART_CONTRACTS("Smart Contracts"),
    ETHICAL_HACKING("Ethical Hacking"),
    REVERSE_ENGINEERING("Reverse Engineering"),
    INCIDENT_RESPONSE("Incident Response"),
    THREAT_INTELLIGENCE("Threat Intelligence"),
    MALWARE_ANALYSIS("Malware Analysis"),
    RISK_ASSESSMENT("Risk Assessment"),
    NETWORK_SECURITY("Network Security"),
    SECURE_CODING_PRACTICES("Secure Coding Practices"),
    CRYPTOGRAPHY_2("Cryptography"),
    DATA_PRIVACY("Data Privacy"),
    CLOUD_SECURITY("Cloud Security"),
    DIGITAL_FORENSICS("Digital Forensics"),
    AGILE_PROJECT_MANAGEMENT("Agile Project Management"),
    WATERFALL_METHODOLOGY("Waterfall Methodology"),
    SOFTWARE_DEVELOPMENT_LIFECYCLE("Software Development Lifecycle"),
    USER_CENTERED_DESIGN("User-Centered Design"),
    INTERACTION_DESIGN("Interaction Design"),
    INFORMATION_ARCHITECTURE("Information Architecture"),
    PROTOTYPING_2("Prototyping"),
    AB_TESTING("A/B Testing"),
    CONTENT_STRATEGY("Content Strategy"),
    BRANDING_IDENTITY_DESIGN("Branding/Identity Design"),
    VIDEO_EDITING("Video Editing"),
    MOTION_GRAPHICS("Motion Graphics"),
    THREE_D_MODELING("3D Modeling"),
    UI_ANIMATION("UI Animation"),
    TYPOGRAPHY("Typography"),
    COLOR_THEORY("Color Theory"),
    ILLUSTRATION("Illustration"),
    CONTENT_WRITING("Content Writing"),
    COPYWRITING("Copywriting"),
    SOCIAL_MEDIA_MARKETING("Social Media Marketing"),
    SEARCH_ENGINE_MARKETING("Search Engine Marketing (SEM)"),
    EMAIL_MARKETING("Email Marketing"),
    GROWTH_HACKING("Growth Hacking"),
    SALES_FUNNEL_OPTIMIZATION("Sales Funnel Optimization"),
    CONVERSION_RATE_OPTIMIZATION("Conversion Rate Optimization (CRO)"),
    INFLUENCER_MARKETING("Influencer Marketing"),
    MOBILE_ADVERTISING("Mobile Advertising"),
    ANALYTICS_REPORTING("Analytics Reporting");

    private final String displayName;

    DevelopmentSkill(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}

