spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:mysql://localhost:3306/babydev
    username: root
    password: babydev1
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail: 
    host: smtp.gmail.com
    port: 587
    username: babydev.noreply@gmail.com
    password: yjovjpwhnyxkuueb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate: DEBUG
logging:
  level:
    org:
      springframework:
        security: DEBUG