spring:
  datasource:
    url: jdbc:mysql://localhost:3306/babydev
    username: root
    password: babydev1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate: DEBUG